name: Build Docker

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/xavescor/youtube-download-bot/youtube-download-bot:latest
          push: ${{ github.ref == '123' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
